baseURL = 'https://sci-sea.github.io/'
languageCode = 'en-us'
title = "My Sci Site"
theme = "PaperMod"
publishDir = "public"
# SEO Essentials
enableRobotsTXT = true
metaDataFormat = "yaml"
description = "Clear site description"

# Sitemap (for search engines)
[sitemap]
  changefreq = "daily"
  priority = 0.5
