baseURL = 'https://sci-sea.github.io/'
languageCode = 'en-us'
title = 'Sci-Sea'
theme = 'PaperMod'
publishDir = 'public'
defaultContentLanguage = 'en'
enableRobotsTXT = true
paginate = 6

[markup]
  [markup.highlight]
    noClasses = false

[params]
  env = "production"
  title = "Sci-Sea"
  description = "Exploring science and the sea"
  author = "Sci-Sea Team"
  ShowReadingTime = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true

  [params.homeInfoParams]
    Title = "Welcome to Sci-Sea"
    Content = "Your gateway to ocean science and discovery."

  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/sci-sea"

[menu]
  [[menu.main]]
    name = "Home"
    pageRef = "/"
    weight = 1

  [[menu.main]]
    name = "Posts"
    pageRef = "/posts"
    weight = 2
    
